### ISSUE TITLE
Select Multi: (de)seleção automática com base nos itens 

### ISSUE THREAD

**Issue by edimarlnx** [tecsinapse/ui-kit#12]
- Ao selecionar todos os itens da lista marcar o item selecionar todos.
- Após ter selecionado todos, ao deselecionar algum, desmarcar a opção selecionar todos.

Criado @oliveirasWell

**Comment by oliveirasWell** [comment]
Já disponível na versão 0.0.56 @edimarlnx 

https://github.com/tecsinapse/ui-kit/commit/ca3694db50c58521dcccabe7d229dee3be03b611

**Comment by edimarlnx** [comment]
Tks @oliveirasWell
