### ISSUE TITLE
Select: select não fecha ao clicar no icon de dropdown 

### ISSUE THREAD

**Issue by edimarlnx** [tecsinapse/ui-kit#40]
Select abre o menu, mas não recolhe ao clicar no icon de dropdown. 

cc @oliveirasWell  @renanccastro

**Comment by oliveirasWell** [comment]
@edimarlnx pode verificar se a última versão está okay?

**Comment by edimarlnx** [comment]
@oliveirasWell  não estava. Fiz um ajuste lá para corrigir o problema.
