### ISSUE TITLE
Fix security alert

### ISSUE THREAD

**Issue by edimarlnx** [tecsinapse/ui-kit#61]
https://github.com/tecsinapse/ui-kit/network/alert/example/yarn.lock/lodash/open

**Comment by bgongre** [comment]
Can you please post a screenshot of the security alert you're receiving? The link does not work.

**Comment by oliveirasWell** [comment]
Done at 2.0.0

**Comment by oliveirasWell** [comment]
Reopen: lodash was not update at `@storybook/react@5.2.0-rc.2`

**Comment by dennervidal** [comment]
Upgrade js-yaml to version 3.13.1: https://github.com/airbnb/babel-plugin-inline-react-svg/issues/45
