### ISSUE TITLE
Create masked prop on input and brazilian default mask(cpf,cnpj,phone,cellphone, currency or money, etc)

### ISSUE THREAD

**Issue by renanccastro** [tecsinapse/ui-kit#8]
Receive mask prop on input, and create brazilian default masks in a variant field(cpf,cnpj,phone,cellphone, plate mask(mercosul format), etc). api example:

<Input maskVariant={ "cpfCnpj" } />

or

<Input mask={ ['\d', '\d' ] } />

The api on input field should be a simple prop(**MASK**) containing an array of options like \d or [1-9], like ['(', /[1-9]/, /\d/, /\d/, ')', ' ', /\d/, /\d/, /\d/, '-', /\d/, /\d/, /\d/, /\d/] OR a function.

Should be compatible with https://github.com/text-mask/text-mask

IMPORTANT: Should have a currency option too, refer to text-mask addon: createNumberMask

- important feature: keyboard type prop (number)

**Comment by felipefutty** [comment]
The currency is not following the Brazilian pattern (without requirement of comma to separate the cents, it assumes the last two digits to be the cents).

This issue track this problem: https://github.com/text-mask/text-mask/issues/263
