### ISSUE TITLE
Circular dependency for react-virtualized

### ISSUE THREAD

**Issue by dennervidal** [tecsinapse/ui-kit#99]
Issue opened in 15 Jan, 19
https://github.com/bvaughn/react-virtualized/issues/1308
No fix yet

**Comment by velusgautam** [comment]
Released a circular dependency fix here. 

https://www.npmjs.com/package/@velusgautam/react-virtualized

Also raised a PR
https://github.com/bvaughn/react-virtualized/pull/1609

**Comment by dennervidal** [comment]
@velusgautam are you planning to maintain and keeps compatible with original lib?

**Comment by velusgautam** [comment]
yes
